/* Guitar Teacher: 50 short lessons in guitar theory.
   Strings are numbered 0-5 from the low E (thickest) to the high E (thinnest).
   Examples: notes = played one after another, together = played at once,
   chord = one strummed chord (frets low E to high E, null = muted), prog = several chords.
   fb = fretboard diagram marks [string, fret, label]; chords = chord diagrams [name, frets]. */
window.SSM_UNITS=['The Fretboard','Intervals and Scales','Chords','Keys and Progressions','Beyond the Basics'];
window.SSM_LESSONS=[
/* ---------- Unit 1: The Fretboard ---------- */
{t:'The musical alphabet',
 body:`<p>Music uses only seven letter names: <b>A B C D E F G</b>. After G, the alphabet starts over at A.</p><p>When you come back around to the same letter, the note sounds higher but has the same character. That distance is called an <b>octave</b>. Play the A string open, then walk up the letters to A at the 12th fret.</p>`,
 ex:[{label:'A to A on the A string',notes:[[1,0],[1,2],[1,3],[1,5],[1,7],[1,8],[1,10],[1,12]]}],
 fb:{marks:[[1,0,'A'],[1,2,'B'],[1,3,'C'],[1,5,'D'],[1,7,'E'],[1,8,'F'],[1,10,'G'],[1,12,'A']]},
 q:{q:'Which letter comes after G?',a:['H','A','G♯','B'],c:1,why:'The musical alphabet stops at G and starts over at A.'}},
{t:'Sharps and flats',
 body:`<p>Between most letters there is an extra note. A <b>sharp (♯)</b> raises a note by one fret; a <b>flat (♭)</b> lowers it by one fret. So the note between C and D can be called C♯ or D♭. Same sound, two names.</p><p>Two pairs have nothing between them: <b>B–C</b> and <b>E–F</b>. That gives 12 different notes before the octave repeats.</p>`,
 ex:[{label:'All 12 notes on the low E string',notes:[[0,0],[0,1],[0,2],[0,3],[0,4],[0,5],[0,6],[0,7],[0,8],[0,9],[0,10],[0,11],[0,12]],tempo:160}],
 fb:{marks:[[0,0,'E'],[0,1,'F'],[0,2,'F♯'],[0,3,'G'],[0,4,'G♯'],[0,5,'A'],[0,6,'A♯'],[0,7,'B'],[0,8,'C'],[0,9,'C♯'],[0,10,'D'],[0,11,'D♯'],[0,12,'E']]},
 q:{q:'Which pair of notes has no note between them?',a:['C and D','E and F','G and A','A and B'],c:1,why:'E–F and B–C are only one fret apart, so there is no sharp or flat between them.'}},
{t:'Half steps and whole steps',
 body:`<p>The smallest distance in Western music is a <b>half step</b>: one fret on the guitar. Two frets make a <b>whole step</b>.</p><p>Almost every scale and chord is described with half and whole steps, so it helps to feel them under your fingers now.</p>`,
 ex:[{label:'Half step: A to A♯',notes:[[1,0],[1,1]]},{label:'Whole step: A to B',notes:[[1,0],[1,2]]}],
 fb:{marks:[[1,0,'A'],[1,1,'A♯'],[1,2,'B']]},
 q:{q:'How many frets make a whole step?',a:['One','Two','Three','Four'],c:1,why:'One fret is a half step, so two frets are a whole step.'}},
{t:'Standard tuning',
 body:`<p>From the thickest string to the thinnest, standard tuning is <b>E A D G B E</b>. A common way to remember it: <i>Eddie Ate Dynamite, Good Bye Eddie</i>.</p><p>Strings are also numbered from the thinnest: the high E is string 1 and the low E is string 6. Tab and chord charts use both systems, so learn both.</p>`,
 ex:[{label:'Open strings, low to high',notes:[[0,0],[1,0],[2,0],[3,0],[4,0],[5,0]]}],
 fb:{marks:[[0,0,'E'],[1,0,'A'],[2,0,'D'],[3,0,'G'],[4,0,'B'],[5,0,'E']]},
 q:{q:'Counting from the thinnest string, which note is string 4?',a:['G','D','A','B'],c:1,why:'String 1 is high E, 2 is B, 3 is G and 4 is D.'}},
{t:'Notes on the low E string',
 body:`<p>The low E string is the home of many chord roots, so it pays to know it cold. Starting open: <b>E F G A B C D E</b> at frets 0, 1, 3, 5, 7, 8, 10 and 12.</p><p>Remember the two half steps: E to F is one fret, and B to C is one fret. Every other letter is two frets apart.</p>`,
 ex:[{label:'Natural notes on low E',notes:[[0,0],[0,1],[0,3],[0,5],[0,7],[0,8],[0,10],[0,12]]}],
 fb:{marks:[[0,0,'E'],[0,1,'F'],[0,3,'G'],[0,5,'A'],[0,7,'B'],[0,8,'C'],[0,10,'D'],[0,12,'E']]},
 q:{q:'What note is at the 5th fret of the low E string?',a:['G','B','A','C'],c:2,why:'E, F (1), G (3), A (5).'}},
{t:'Notes on the A string',
 body:`<p>The A string is the other home for chord roots. Starting open: <b>A B C D E F G A</b> at frets 0, 2, 3, 5, 7, 8, 10 and 12.</p><p>Tip: a note on the low E string and the note on the A string at the same fret are always a fourth apart. Once you know one string, you can find the other quickly.</p>`,
 ex:[{label:'Natural notes on the A string',notes:[[1,0],[1,2],[1,3],[1,5],[1,7],[1,8],[1,10],[1,12]]}],
 fb:{marks:[[1,0,'A'],[1,2,'B'],[1,3,'C'],[1,5,'D'],[1,7,'E'],[1,8,'F'],[1,10,'G'],[1,12,'A']]},
 q:{q:'Where is C on the A string?',a:['2nd fret','3rd fret','5th fret','8th fret'],c:1,why:'A (0), B (2), C (3). B to C is a half step.'}},
{t:'Octave shapes',
 body:`<p>You can find the same note an octave higher with a shape. From the low E or A string: go <b>two strings up and two frets higher</b>.</p><p>From the D or G string, go two strings up and <b>three</b> frets higher. The extra fret is because the B string is tuned one fret lower than the pattern expects.</p>`,
 ex:[{label:'A on low E, then A on the D string',notes:[[0,5],[2,7]]},{label:'A on the G string, then A on high E',notes:[[3,2],[5,5]]}],
 fb:{marks:[[0,5,'A'],[2,7,'A'],[3,2,'A'],[5,5,'A']]},
 q:{q:'C is at the 3rd fret of the A string. Where is the next C up?',a:['D string, 5th fret','G string, 5th fret','G string, 3rd fret','B string, 5th fret'],c:1,why:'From the A string, go two strings up (to G) and two frets higher (to 5).'}},
{t:'Tuning by the fifth fret',
 body:`<p>The 5th fret of each string makes the same note as the next open string. Low E at the 5th fret is A, the same as the open A string.</p><p>The exception is the G string: use its <b>4th fret</b> to match the open B. If you have one string in tune, this lets you tune the rest by ear.</p>`,
 ex:[{label:'Low E 5th fret, then open A',notes:[[0,5],[1,0]]},{label:'G string 4th fret, then open B',notes:[[3,4],[4,0]]}],
 fb:{marks:[[0,5,'A'],[1,5,'D'],[2,5,'G'],[3,4,'B'],[4,5,'E']]},
 q:{q:'Which fret on the G string matches the open B?',a:['3rd','4th','5th','7th'],c:1,why:'G and B are four frets apart, so the G string uses the 4th fret instead of the 5th.'}},
{t:'The 12th fret starts it over',
 body:`<p>Twelve frets is one octave, so the whole fretboard repeats after the 12th fret. The 15th fret has the same note names as the 3rd, the 17th as the 5th, and so on.</p><p>The dots on the neck help you keep your place: usually at frets 3, 5, 7, 9 and a double dot at 12.</p>`,
 ex:[{label:'Open E and 12th fret E',notes:[[0,0],[0,12]]},{label:'C at fret 3 and fret 15',notes:[[1,3],[1,15]]}],
 fb:{marks:[[0,0,'E'],[0,12,'E'],[1,3,'C']]},
 q:{q:'What note is at the 15th fret of the A string?',a:['B','C','D','A'],c:1,why:'15 is 12 + 3, and the 3rd fret of the A string is C.'}},
{t:'Reading tab',
 body:`<p><b>Tab</b> shows guitar music as six lines, one per string. The <b>top line is the high E</b> and the bottom line is the low E, as if you were looking down at the neck.</p><p>Numbers are frets. Read left to right, and play numbers that are stacked on top of each other at the same time.</p><pre class="tab">e|-----------0---|
B|-------1-------|
G|---0-------0---|
D|-2-------2-----|
A|---------------|
E|---------------|</pre>`,
 ex:[{label:'Play the tab above',notes:[[2,2],[3,0],[4,1],[5,0],[2,2],[3,0]],tempo:100}],
 q:{q:'In tab, the bottom line stands for…',a:['the high E string','the low E string','the first fret','the loudest note'],c:1,why:'The bottom line is the thickest string, low E. The top line is high E.'}},

/* ---------- Unit 2: Intervals and Scales ---------- */
{t:'What an interval is',
 body:`<p>An <b>interval</b> is the distance between two notes, counted in half steps. From A up to C is three half steps; from A to the next A is twelve.</p><p>Every interval has its own sound, and chords are just stacks of intervals. Learning to hear them is the start of playing by ear.</p>`,
 ex:[{label:'A to C (3 half steps)',notes:[[1,0],[1,3]]},{label:'A to A (12 half steps)',notes:[[1,0],[1,12]]}],
 q:{q:'How many half steps are in an octave?',a:['7','8','10','12'],c:3,why:'There are 12 different notes, so an octave is 12 half steps.'}},
{t:'Major and minor thirds',
 body:`<p>A <b>major third</b> is 4 half steps. It sounds bright. A <b>minor third</b> is 3 half steps. It sounds darker.</p><p>The third is what makes a chord major or minor, so these two intervals are among the most important in music.</p>`,
 ex:[{label:'Major third: C and E together',together:[[1,3],[2,2]]},{label:'Minor third: C and E♭ together',together:[[1,3],[2,1]]}],
 fb:{marks:[[1,3,'C'],[2,2,'E'],[2,1,'E♭']]},
 q:{q:'C up to E♭ is a…',a:['major third','minor third','perfect fourth','major second'],c:1,why:'C to E♭ is 3 half steps, which is a minor third.'}},
{t:'The perfect fifth',
 body:`<p>A <b>perfect fifth</b> is 7 half steps. It sounds strong and open, with no happy or sad color.</p><p>On the low E, A and D strings, the fifth is on the next string up at the <b>same fret plus two</b>. This shape is the power chord you will meet later.</p>`,
 ex:[{label:'C and G together',together:[[1,3],[2,5]]},{label:'E and B together',together:[[0,0],[1,2]]}],
 fb:{marks:[[1,3,'C'],[2,5,'G'],[0,0,'E'],[1,2,'B']]},
 q:{q:'What note is a perfect fifth above A?',a:['D','E','F','C'],c:1,why:'A, B, C, D, E: E is five letters up and 7 half steps above A.'}},
{t:'The fourth and the octave',
 body:`<p>A <b>perfect fourth</b> is 5 half steps. Most neighboring open strings on the guitar are a fourth apart: E–A, A–D, D–G and B–E. Only G–B is different: it is a major third.</p><p>The <b>octave</b> is 12 half steps: the same note name, higher.</p>`,
 ex:[{label:'Open E and A together (a fourth)',together:[[0,0],[1,0]]},{label:'Open G and B together (a third)',together:[[3,0],[4,0]]}],
 q:{q:'Most neighboring open strings are how far apart?',a:['A major third','A perfect fourth','A perfect fifth','An octave'],c:1,why:'E–A, A–D, D–G and B–E are all perfect fourths. G–B is the one major third.'}},
{t:'Seconds, sixths and sevenths',
 body:`<p>The rest of the intervals, counted in half steps: <b>minor second</b> 1, <b>major second</b> 2, <b>minor sixth</b> 8, <b>major sixth</b> 9, <b>minor seventh</b> 10, <b>major seventh</b> 11.</p><p>Seconds sound tight, sixths sound sweet, and sevenths sound like they want to move somewhere.</p>`,
 ex:[{label:'Major sixth: C up to A',notes:[[1,3],[3,2]]},{label:'Minor seventh: C up to B♭',notes:[[1,3],[3,3]]},{label:'Major seventh: C up to B',notes:[[1,3],[3,4]]}],
 q:{q:'How many half steps are in a minor seventh?',a:['9','10','11','8'],c:1,why:'A minor seventh is 10 half steps: two less than an octave.'}},
{t:'The tritone',
 body:`<p>The <b>tritone</b> is 6 half steps, exactly half an octave. It sounds tense and unsettled, as if it needs to resolve.</p><p>That tension is useful. A dominant seventh chord like G7 contains a tritone (B and F), which is why it pulls so strongly back to C.</p>`,
 ex:[{label:'C and F♯ together',together:[[1,3],[2,4]]},{label:'Tritone resolving: B and F, then C and E',seq:[{together:[[1,2],[2,3]]},{together:[[1,3],[2,2]]}]}],
 q:{q:'B up to F is a…',a:['perfect fifth','tritone','perfect fourth','minor sixth'],c:1,why:'B to F is 6 half steps (B, C, C♯, D, D♯, E, F), which is a tritone.'}},
{t:'The major scale formula',
 body:`<p>Every major scale follows the same pattern of steps: <b>W W H W W W H</b> (whole, whole, half, whole, whole, whole, half).</p><p>Start on C and follow the pattern and you get C D E F G A B C: no sharps or flats. Start on any other note and the pattern tells you which sharps or flats you need.</p>`,
 ex:[{label:'C major scale',notes:[[1,3],[1,5],[2,2],[2,3],[2,5],[3,2],[3,4],[3,5]]}],
 fb:{marks:[[1,3,'C'],[1,5,'D'],[2,2,'E'],[2,3,'F'],[2,5,'G'],[3,2,'A'],[3,4,'B'],[3,5,'C']]},
 q:{q:'In a major scale, the half steps fall between which degrees?',a:['1–2 and 5–6','3–4 and 7–8','2–3 and 6–7','4–5 and 7–8'],c:1,why:'W W H W W W H puts the half steps after the 3rd and 7th degrees.'}},
{t:'A major scale on one string',
 body:`<p>Playing a scale along one string shows the step pattern clearly. G major on the low E string starts at the 3rd fret: frets <b>3 5 7 8 10 12 14 15</b>.</p><p>The gaps match W W H W W W H exactly. The 7th note lands on F♯, the one sharp in G major.</p>`,
 ex:[{label:'G major on low E',notes:[[0,3],[0,5],[0,7],[0,8],[0,10],[0,12],[0,14],[0,15]]}],
 fb:{frets:15,marks:[[0,3,'G'],[0,5,'A'],[0,7,'B'],[0,8,'C'],[0,10,'D'],[0,12,'E'],[0,14,'F♯'],[0,15,'G']]},
 q:{q:'Which note in G major has a sharp?',a:['C','F','D','G'],c:1,why:'Following W W H W W W H from G gives G A B C D E F♯ G.'}},
{t:'Scale degrees',
 body:`<p>Musicians number the notes of a scale from <b>1 to 7</b>. In C major, 1 is C, 3 is E, 5 is G. These numbers are called <b>scale degrees</b>.</p><p>Numbers let you talk about music in any key. "Play 1, 3 and 5" means C E G in C major and G B D in G major. Singers use the same idea with do, re, mi.</p>`,
 ex:[{label:'1, 3 and 5 in C major',notes:[[1,3],[2,2],[3,0]]},{label:'1, 3 and 5 in G major',notes:[[0,3],[1,2],[2,0]]}],
 q:{q:'In G major, which note is degree 5?',a:['C','D','E','B'],c:1,why:'G major is G A B C D E F♯, so the 5th note is D.'}},
{t:'The natural minor scale',
 body:`<p>The <b>natural minor</b> scale uses the pattern <b>W H W W H W W</b>. It sounds darker than major.</p><p>A minor is A B C D E F G: the same notes as C major, starting from A. That is no accident. Every major scale has a minor scale hiding inside it, starting on its 6th degree.</p>`,
 ex:[{label:'A natural minor',notes:[[1,0],[1,2],[1,3],[2,0],[2,2],[2,3],[3,0],[3,2]]}],
 fb:{marks:[[1,0,'A'],[1,2,'B'],[1,3,'C'],[2,0,'D'],[2,2,'E'],[2,3,'F'],[3,0,'G'],[3,2,'A']]},
 q:{q:'How many sharps or flats are in A natural minor?',a:['None','One','Two','Three'],c:0,why:'A minor uses the same notes as C major: A B C D E F G.'}},

/* ---------- Unit 3: Chords ---------- */
{t:'What a triad is',
 body:`<p>A <b>triad</b> is a three-note chord made by stacking thirds: a <b>root</b>, a <b>third</b> above it, and a <b>fifth</b> above the root.</p><p>Guitar chords often have five or six strings ringing, but they are usually just these three notes repeated in different octaves.</p>`,
 ex:[{label:'C, E, G one at a time',notes:[[1,3],[2,2],[3,0]]},{label:'Then together',together:[[1,3],[2,2],[3,0]]}],
 fb:{marks:[[1,3,'R'],[2,2,'3'],[3,0,'5']]},
 q:{q:'A triad is built by stacking…',a:['seconds','thirds','fourths','octaves'],c:1,why:'Root, third and fifth: each note is a third above the one before.'}},
{t:'The major triad',
 body:`<p>A <b>major triad</b> is a root, a <b>major third</b> (4 half steps) and a <b>perfect fifth</b> (7 half steps). C major is C E G. G major is G B D.</p><p>Look at an open C chord and you will find only C, E and G on the strings you play.</p>`,
 ex:[{label:'C major',chord:[null,3,2,0,1,0]},{label:'G major',chord:[3,2,0,0,0,3]}],
 chords:[['C',[null,3,2,0,1,0]],['G',[3,2,0,0,0,3]]],
 q:{q:'What notes are in D major?',a:['D F A','D F♯ A','D G A','D F♯ B'],c:1,why:'A major third above D is F♯, and a perfect fifth above D is A.'}},
{t:'The minor triad',
 body:`<p>A <b>minor triad</b> keeps the root and fifth but lowers the third by one half step, to a <b>minor third</b>. A minor is A C E. E minor is E G B.</p><p>Compare A major and A minor: only one note changes, but the mood changes completely.</p>`,
 ex:[{label:'A major',chord:[null,0,2,2,2,0]},{label:'A minor',chord:[null,0,2,2,1,0]}],
 chords:[['A',[null,0,2,2,2,0]],['Am',[null,0,2,2,1,0]]],
 q:{q:'To turn D major into D minor, which note do you lower?',a:['The root','The third','The fifth','All of them'],c:1,why:'Lowering the third (F♯ to F) makes D minor: D F A.'}},
{t:'Diminished and augmented',
 body:`<p>Two more triads. <b>Diminished</b> stacks two minor thirds: B D F. It sounds tense and unstable. <b>Augmented</b> stacks two major thirds: C E G♯. It sounds dreamy and unresolved.</p><p>You will hear them less often, usually as passing chords on the way somewhere else.</p>`,
 ex:[{label:'B diminished',chord:[null,2,3,4,3,null]},{label:'C augmented',chord:[null,3,2,1,1,0]}],
 chords:[['Bdim',[null,2,3,4,3,null]],['Caug',[null,3,2,1,1,0]]],
 q:{q:'Which triad stacks two major thirds?',a:['Major','Minor','Diminished','Augmented'],c:3,why:'Two major thirds make an augmented triad, like C E G♯.'}},
{t:'Reading chord diagrams',
 body:`<p>A chord diagram is a picture of the neck standing up. <b>Vertical lines are strings</b> (low E on the left), <b>horizontal lines are frets</b>, and dots show where your fingers go.</p><p>An <b>O</b> above a string means play it open. An <b>X</b> means don't play it. The thick line at the top is the nut.</p>`,
 ex:[{label:'C major',chord:[null,3,2,0,1,0]},{label:'D major',chord:[null,null,0,2,3,2]}],
 chords:[['C',[null,3,2,0,1,0]],['D',[null,null,0,2,3,2]]],
 q:{q:'An X above a string on a chord diagram means…',a:['Play it open','Don\'t play it','Use your thumb','Bend it'],c:1,why:'X marks a string you mute or skip. O marks an open string.'}},
{t:'Open chords and CAGED',
 body:`<p>The five open major chord shapes are <b>C, A, G, E and D</b>. Together they spell CAGED.</p><p>Each shape can be moved up the neck with a barre or a capo, and the five shapes link together end to end along the fretboard. Learning them is a map to playing any chord anywhere on the neck.</p>`,
 ex:[{label:'C A G E D',prog:[[null,3,2,0,1,0],[null,0,2,2,2,0],[3,2,0,0,0,3],[0,2,2,1,0,0],[null,null,0,2,3,2]]}],
 chords:[['C',[null,3,2,0,1,0]],['A',[null,0,2,2,2,0]],['G',[3,2,0,0,0,3]],['E',[0,2,2,1,0,0]],['D',[null,null,0,2,3,2]]],
 q:{q:'What does CAGED refer to?',a:['A strumming pattern','Five open chord shapes','A type of tuning','The order of sharps'],c:1,why:'C, A, G, E and D are the five open major chord shapes.'}},
{t:'Power chords',
 body:`<p>A <b>power chord</b> is just a root and a fifth, often with the octave on top. It has <b>no third</b>, so it is neither major nor minor.</p><p>That makes it sound clean even with lots of distortion, which is why rock and punk lean on it. The shape is movable: slide it anywhere and the root note names the chord.</p>`,
 ex:[{label:'E5, G5, A5',prog:[[0,2,2,null,null,null],[3,5,5,null,null,null],[5,7,7,null,null,null]],dirty:true}],
 chords:[['E5',[0,2,2,null,null,null]],['G5',[3,5,5,null,null,null]]],
 q:{q:'Why is a power chord neither major nor minor?',a:['It has no root','It has no third','It has no fifth','It is too loud'],c:1,why:'The third decides major or minor, and power chords leave it out.'}},
{t:'Barre chords: the E shape',
 body:`<p>Lay your index finger across all six strings and form an E chord shape with your other fingers just above it. That is an <b>E-shape barre chord</b>.</p><p>The root is on the low E string, so the chord is named after that note. At the 1st fret it is F; at the 3rd fret, G; at the 5th, A. Use the E minor shape instead for minor chords.</p>`,
 ex:[{label:'F, G, A',prog:[[1,3,3,2,1,1],[3,5,5,4,3,3],[5,7,7,6,5,5]]},{label:'F minor',chord:[1,3,3,1,1,1]}],
 chords:[['F',[1,3,3,2,1,1]],['Fm',[1,3,3,1,1,1]]],
 q:{q:'An E-shape barre at the 7th fret is which chord?',a:['A major','B major','C major','E major'],c:1,why:'The low E string at the 7th fret is B, so it is B major.'}},
{t:'Barre chords: the A shape',
 body:`<p>The <b>A-shape barre</b> puts the root on the A string. Bar across from the A string and form an A chord shape above it.</p><p>At the 1st fret it is B♭; at the 3rd, C; at the 5th, D. With the E and A shapes together, you can play every major and minor chord without moving far.</p>`,
 ex:[{label:'B♭, C, D',prog:[[null,1,3,3,3,1],[null,3,5,5,5,3],[null,5,7,7,7,5]]},{label:'C minor',chord:[null,3,5,5,4,3]}],
 chords:[['C',[null,3,5,5,5,3]],['Cm',[null,3,5,5,4,3]]],
 q:{q:'An A-shape minor barre at the 5th fret is which chord?',a:['A minor','D minor','E minor','C minor'],c:1,why:'The A string at the 5th fret is D, so the chord is D minor.'}},
{t:'Seventh chords',
 body:`<p>Add one more third on top of a triad and you get a <b>seventh chord</b>. Three common types:</p><p><b>Major 7</b> (Cmaj7): major triad plus a major seventh. Soft and dreamy. <b>Dominant 7</b> (G7): major triad plus a minor seventh. Bluesy and restless. <b>Minor 7</b> (Am7): minor triad plus a minor seventh. Smooth and mellow.</p>`,
 ex:[{label:'Cmaj7',chord:[null,3,2,0,0,0]},{label:'G7',chord:[3,2,0,0,0,1]},{label:'Am7',chord:[null,0,2,0,1,0]}],
 chords:[['Cmaj7',[null,3,2,0,0,0]],['G7',[3,2,0,0,0,1]],['Am7',[null,0,2,0,1,0]]],
 q:{q:'Which chord is a major triad with a minor seventh?',a:['Major 7','Minor 7','Dominant 7','Diminished'],c:2,why:'Dominant 7 = major triad + minor seventh, like G B D F.'}},

/* ---------- Unit 4: Keys and Progressions ---------- */
{t:'What a key is',
 body:`<p>A song's <b>key</b> is the scale its notes mostly come from, plus a home note called the <b>tonic</b>. A song in G major uses the G major scale and feels finished when it lands on G.</p><p>Knowing the key tells you which chords will fit and which notes to use when you solo.</p>`,
 ex:[{label:'G, C, D, back home to G',prog:[[3,2,0,0,0,3],[null,3,2,0,1,0],[null,null,0,2,3,2],[3,2,0,0,0,3]]}],
 q:{q:'The home note of a key is called the…',a:['root chord','tonic','dominant','octave'],c:1,why:'The tonic is the note (and chord) a key resolves to.'}},
{t:'The chords in a major key',
 body:`<p>Build a triad on each note of a major scale, using only notes from that scale, and you get seven chords. Their qualities always fall in the same order: <b>major, minor, minor, major, major, minor, diminished</b>.</p><p>In C major that gives C, Dm, Em, F, G, Am and B°. Those seven chords will fit together in any song in C.</p>`,
 ex:[{label:'C Dm Em F G Am',prog:[[null,3,2,0,1,0],[null,null,0,2,3,1],[0,2,2,0,0,0],[1,3,3,2,1,1],[3,2,0,0,0,3],[null,0,2,2,1,0]]}],
 chords:[['C',[null,3,2,0,1,0]],['Dm',[null,null,0,2,3,1]],['Em',[0,2,2,0,0,0]],['F',[1,3,3,2,1,1]],['G',[3,2,0,0,0,3]],['Am',[null,0,2,2,1,0]]],
 q:{q:'In C major, which chord is built on the 6th degree?',a:['F major','A minor','G major','E minor'],c:1,why:'The 6th note of C major is A, and the 6th chord in a major key is minor.'}},
{t:'Roman numerals',
 body:`<p>Musicians label key chords with Roman numerals: <b>I ii iii IV V vi vii°</b>. Uppercase means major, lowercase means minor, and ° means diminished.</p><p>Numerals make progressions portable. I–IV–V is C–F–G in C major, G–C–D in G major and A–D–E in A major. Learn the numbers and you can play a song in any key.</p>`,
 ex:[{label:'I–IV–V in G',prog:[[3,2,0,0,0,3],[null,3,2,0,1,0],[null,null,0,2,3,2]]},{label:'I–IV–V in A',prog:[[null,0,2,2,2,0],[null,null,0,2,3,2],[0,2,2,1,0,0]]}],
 q:{q:'In D major, what is the IV chord?',a:['E minor','G major','A major','F♯ minor'],c:1,why:'D major is D E F♯ G A B C♯. The 4th degree is G, and IV is major.'}},
{t:'The I–IV–V',
 body:`<p>The three major chords in a key, <b>I, IV and V</b>, are enough for thousands of songs: early rock and roll, folk, country and nearly all blues.</p><p>V has the strongest pull back to I. Listen for the tension on the V chord and the relief when it resolves.</p>`,
 ex:[{label:'A, D, E, A',prog:[[null,0,2,2,2,0],[null,null,0,2,3,2],[0,2,2,1,0,0],[null,0,2,2,2,0]]}],
 chords:[['A',[null,0,2,2,2,0]],['D',[null,null,0,2,3,2]],['E',[0,2,2,1,0,0]]],
 q:{q:'What are I, IV and V in E major?',a:['E, A, B','E, G, A','E, A, D','E, B, C♯'],c:0,why:'E major is E F♯ G♯ A B C♯ D♯, so I is E, IV is A and V is B.'}},
{t:'The I–V–vi–IV',
 body:`<p><b>I–V–vi–IV</b> may be the most common progression in pop music. In C major it is C–G–Am–F. In G it is G–D–Em–C.</p><p>It works because it mixes the stable major chords with one minor chord for a touch of emotion, then circles back to the start.</p>`,
 ex:[{label:'G, D, Em, C',prog:[[3,2,0,0,0,3],[null,null,0,2,3,2],[0,2,2,0,0,0],[null,3,2,0,1,0]]}],
 chords:[['G',[3,2,0,0,0,3]],['D',[null,null,0,2,3,2]],['Em',[0,2,2,0,0,0]],['C',[null,3,2,0,1,0]]],
 q:{q:'What is the vi chord in G major?',a:['C major','E minor','A minor','B minor'],c:1,why:'The 6th note of G major is E, and vi is minor: E minor.'}},
{t:'The ii–V–I',
 body:`<p>The <b>ii–V–I</b> is the backbone of jazz. It is usually played with seventh chords: in C major, <b>Dm7–G7–Cmaj7</b>.</p><p>Each chord root moves down a fifth to the next, which gives the progression a smooth, inevitable pull toward home.</p>`,
 ex:[{label:'Dm7, G7, Cmaj7',prog:[[null,null,0,2,1,1],[3,2,0,0,0,1],[null,3,2,0,0,0]]}],
 chords:[['Dm7',[null,null,0,2,1,1]],['G7',[3,2,0,0,0,1]],['Cmaj7',[null,3,2,0,0,0]]],
 q:{q:'What is ii–V–I in F major?',a:['Gm–C–F','Dm–G–C','Am–D–G','Gm–D–F'],c:0,why:'F major is F G A B♭ C D E: ii is G minor, V is C, I is F.'}},
{t:'The 12-bar blues',
 body:`<p>The <b>12-bar blues</b> is a fixed 12-measure form built from I, IV and V, usually as dominant seventh chords:</p><p><code>I I I I | IV IV I I | V IV I V</code></p><p>The last bar, the V, is a turnaround that sends you back to the top. Here it is in A with one strum per bar.</p>`,
 ex:[{label:'12 bars in A',prog:[[null,0,2,0,2,0],[null,0,2,0,2,0],[null,0,2,0,2,0],[null,0,2,0,2,0],[null,null,0,2,1,2],[null,null,0,2,1,2],[null,0,2,0,2,0],[null,0,2,0,2,0],[0,2,0,1,0,0],[null,null,0,2,1,2],[null,0,2,0,2,0],[0,2,0,1,0,0]],tempo:170}],
 chords:[['A7',[null,0,2,0,2,0]],['D7',[null,null,0,2,1,2]],['E7',[0,2,0,1,0,0]]],
 q:{q:'In a 12-bar blues in A, which chord is in bar 5?',a:['A7','D7','E7','B7'],c:1,why:'Bar 5 is the IV chord. In A, IV is D, so D7.'}},
{t:'Relative major and minor',
 body:`<p>Every major key shares its notes with a minor key: its <b>relative minor</b>, which starts on the 6th degree. C major and A minor share the same notes; so do G major and E minor.</p><p>On the guitar, the relative minor is always <b>three frets below</b> the major tonic.</p>`,
 ex:[{label:'C major, then A minor',prog:[[null,3,2,0,1,0],[null,0,2,2,1,0]]},{label:'G major, then E minor',prog:[[3,2,0,0,0,3],[0,2,2,0,0,0]]}],
 q:{q:'What is the relative minor of D major?',a:['A minor','B minor','E minor','F♯ minor'],c:1,why:'The 6th degree of D major is B, three half steps below D.'}},
{t:'The circle of fifths',
 body:`<p>Start at C (no sharps) and go up a fifth each time: <b>C G D A E B F♯</b>. Each step adds one sharp. Go the other way, up a fourth each time: <b>F B♭ E♭ A♭ D♭ G♭</b>, and each step adds one flat.</p><p>Keys next to each other on the circle share six of their seven notes, which is why songs often move between neighbors.</p>`,
 ex:[{label:'Around the circle: C G D A E',prog:[[null,3,2,0,1,0],[3,2,0,0,0,3],[null,null,0,2,3,2],[null,0,2,2,2,0],[0,2,2,1,0,0]]}],
 q:{q:'How many sharps does A major have?',a:['2','3','4','1'],c:1,why:'C (0), G (1), D (2), A (3). A major has F♯, C♯ and G♯.'}},
{t:'Using a capo',
 body:`<p>A <b>capo</b> clamps across the neck and acts like a new nut. Your chord shapes stay the same, but everything sounds higher.</p><p>Each fret raises the pitch a half step. A G shape with the capo on the 2nd fret sounds like A. Guitarists use this to fit a singer's range while keeping easy open shapes.</p>`,
 ex:[{label:'G shape, no capo',chord:[3,2,0,0,0,3]},{label:'G shape, capo on 2 (sounds as A)',chord:[5,4,2,2,2,5]}],
 q:{q:'A C shape with the capo on the 3rd fret sounds as…',a:['D','E♭','E','F'],c:1,why:'Three half steps above C is E♭ (C♯, D, E♭).'}},

/* ---------- Unit 5: Beyond the Basics ---------- */
{t:'The minor pentatonic scale',
 body:`<p>The <b>minor pentatonic</b> has five notes: <b>1, ♭3, 4, 5, ♭7</b>. In A that is A C D E G.</p><p>Its first box shape at the 5th fret is the most used pattern in rock and blues soloing: two notes per string, and it is hard to hit a wrong note.</p>`,
 ex:[{label:'A minor pentatonic, box 1',notes:[[0,5],[0,8],[1,5],[1,7],[2,5],[2,7],[3,5],[3,7],[4,5],[4,8],[5,5],[5,8]],tempo:140}],
 fb:{marks:[[0,5,'A'],[0,8,'C'],[1,5,'D'],[1,7,'E'],[2,5,'G'],[2,7,'A'],[3,5,'C'],[3,7,'D'],[4,5,'E'],[4,8,'G'],[5,5,'A'],[5,8,'C']]},
 q:{q:'How many different notes are in a pentatonic scale?',a:['5','6','7','8'],c:0,why:'Penta means five: 1, ♭3, 4, 5 and ♭7 in the minor version.'}},
{t:'The major pentatonic scale',
 body:`<p>The <b>major pentatonic</b> is <b>1, 2, 3, 5, 6</b>. C major pentatonic is C D E G A: the same notes as A minor pentatonic.</p><p>So one box shape does double duty. Play the minor box starting from the relative minor and you are playing the major pentatonic, which sounds sweet and country-flavored.</p>`,
 ex:[{label:'C major pentatonic',notes:[[1,3],[1,5],[2,2],[2,5],[3,2],[3,5]]}],
 fb:{marks:[[1,3,'C'],[1,5,'D'],[2,2,'E'],[2,5,'G'],[3,2,'A'],[3,5,'C']]},
 q:{q:'C major pentatonic has the same notes as…',a:['C minor pentatonic','A minor pentatonic','G minor pentatonic','E minor pentatonic'],c:1,why:'A is the relative minor of C, so their pentatonic scales share all five notes.'}},
{t:'The blues scale',
 body:`<p>Add one note to the minor pentatonic, the <b>♭5</b>, and you have the <b>blues scale</b>: 1, ♭3, 4, ♭5, 5, ♭7. In A: A C D E♭ E G.</p><p>The ♭5 is called the <b>blue note</b>. Don't sit on it; slide through it between the 4 and the 5.</p>`,
 ex:[{label:'D, E♭, E on the A string',notes:[[1,5],[1,6],[1,7]]},{label:'Blues lick',notes:[[3,5],[3,7],[3,8],[3,7],[3,5],[2,7]],tempo:130}],
 fb:{marks:[[1,5,'D'],[1,6,'E♭'],[1,7,'E'],[3,8,'E♭']]},
 q:{q:'What is the blue note in the A blues scale?',a:['B','E♭','F♯','C♯'],c:1,why:'The blue note is the ♭5. The 5th of A is E, so ♭5 is E♭.'}},
{t:'The Dorian mode',
 body:`<p>A <b>mode</b> is a major scale started from a different note. <b>Dorian</b> starts on the 2nd degree: D Dorian uses the notes of C major, from D to D.</p><p>Compared with natural minor, Dorian has a <b>raised 6th</b>. It sounds minor but a little brighter and jazzier.</p>`,
 ex:[{label:'D Dorian on the D string',notes:[[2,0],[2,2],[2,3],[2,5],[2,7],[2,9],[2,10],[2,12]]}],
 fb:{marks:[[2,0,'D'],[2,2,'E'],[2,3,'F'],[2,5,'G'],[2,7,'A'],[2,9,'B'],[2,10,'C'],[2,12,'D']]},
 q:{q:'Which note makes D Dorian different from D natural minor?',a:['E','B natural instead of B♭','F♯','C♯'],c:1,why:'D natural minor has B♭. Dorian raises the 6th to B.'}},
{t:'The Mixolydian mode',
 body:`<p><b>Mixolydian</b> starts on the 5th degree of the major scale. G Mixolydian uses C major notes from G to G: G A B C D E F.</p><p>It is a major scale with a <b>lowered 7th</b>. That ♭7 gives it the relaxed, bluesy sound of classic rock and jam bands, and it fits perfectly over dominant 7 chords.</p>`,
 ex:[{label:'G Mixolydian on low E',notes:[[0,3],[0,5],[0,7],[0,8],[0,10],[0,12],[0,13],[0,15]]}],
 fb:{frets:15,marks:[[0,3,'G'],[0,5,'A'],[0,7,'B'],[0,8,'C'],[0,10,'D'],[0,12,'E'],[0,13,'F'],[0,15,'G']]},
 q:{q:'Mixolydian is a major scale with which note lowered?',a:['The 3rd','The 6th','The 7th','The 4th'],c:2,why:'Mixolydian has a ♭7, like G to F natural instead of F♯.'}},
{t:'The seven modes',
 body:`<p>Start the major scale on each of its seven notes and you get seven modes: <b>Ionian</b> (1, the major scale), <b>Dorian</b> (2), <b>Phrygian</b> (3), <b>Lydian</b> (4), <b>Mixolydian</b> (5), <b>Aeolian</b> (6, natural minor) and <b>Locrian</b> (7).</p><p>From brightest to darkest: Lydian, Ionian, Mixolydian, Dorian, Aeolian, Phrygian, Locrian. Phrygian's ♭2 gives a Spanish flavor; Lydian's ♯4 sounds floating and cinematic.</p>`,
 ex:[{label:'E Phrygian',notes:[[0,0],[0,1],[0,3],[0,5],[0,7],[0,8],[0,10],[0,12]]},{label:'F Lydian',notes:[[0,1],[0,3],[0,5],[0,7],[0,8],[0,10],[0,12],[0,13]]}],
 q:{q:'Which mode starts on the 4th degree of the major scale?',a:['Dorian','Lydian','Mixolydian','Phrygian'],c:1,why:'Ionian 1, Dorian 2, Phrygian 3, Lydian 4.'}},
{t:'Note values and counting',
 body:`<p>Most music is in <b>4/4</b>: four beats per bar. A <b>whole note</b> lasts 4 beats, a <b>half note</b> 2, a <b>quarter note</b> 1, an <b>eighth note</b> ½ and a <b>sixteenth note</b> ¼.</p><p>Count eighths as "1 and 2 and 3 and 4 and", and sixteenths as "1 e and a 2 e and a". Counting out loud is the fastest way to lock in with a drummer.</p>`,
 ex:[{label:'Quarters, eighths, then sixteenths',rhythm:[1,1,1,1,.5,.5,.5,.5,.5,.5,.5,.5,.25,.25,.25,.25,.25,.25,.25,.25,.25,.25,.25,.25,.25,.25,.25,.25],tempo:90}],
 q:{q:'How many eighth notes fit in one bar of 4/4?',a:['4','6','8','16'],c:2,why:'Each beat holds two eighth notes, and 4 × 2 = 8.'}},
{t:'Strumming patterns',
 body:`<p>Keep your strumming hand moving down and up in steady eighth notes, even when you don't hit the strings. <b>Downstrokes land on the beats</b> and <b>upstrokes on the "ands"</b>.</p><p>A classic pattern is <code>D - D U - U D U</code>: down on 1, down-up on 2 and, skip beat 3, up on the "and" of 3, then down-up on 4 and.</p>`,
 ex:[{label:'D D U U D U on G major',pattern:true,chord:[3,2,0,0,0,3]}],
 q:{q:'In eighth-note strumming, upstrokes usually land on…',a:['the beats','the "ands"','every other bar','only beat 3'],c:1,why:'Downstrokes are on 1 2 3 4; upstrokes are on the "and" between them.'}},
{t:'Natural harmonics',
 body:`<p>Touch a string lightly, right above the fret wire, without pressing it down, and pluck. You get a bell-like <b>harmonic</b>.</p><p>At the 12th fret it sounds an octave up. At the 7th fret it sounds an octave and a fifth up. At the 5th fret it sounds two octaves up. They work because you are dividing the string into halves, thirds and quarters.</p>`,
 ex:[{label:'Low E harmonics at 12, 7 and 5',harm:[[0,12],[0,19],[0,24]]}],
 q:{q:'A natural harmonic at the 7th fret sounds…',a:['an octave up','a fifth up','an octave and a fifth up','two octaves up'],c:2,why:'The 7th fret divides the string into thirds, which sounds an octave and a fifth above the open string.'}},
{t:'Putting it all together',
 body:`<p>Here is everything at once. The progression <b>Am–F–C–G</b> is i–VI–III–VII in A minor. The <b>A minor pentatonic</b> box at the 5th fret fits over all of it.</p><p>Try this: strum the progression, then play the lick below, and aim to end phrases on a note from the chord underneath. From here, write your own riff in Riff Roulette and post it on the wall.</p>`,
 ex:[{label:'Am, F, C, G',prog:[[null,0,2,2,1,0],[1,3,3,2,1,1],[null,3,2,0,1,0],[3,2,0,0,0,3]]},{label:'A minor pentatonic lick',notes:[[5,8],[5,5],[4,8],[4,5],[3,7],[3,5],[2,7]],tempo:110}],
 q:{q:'Which scale fits over Am–F–C–G?',a:['A minor pentatonic','A major pentatonic','E blues','D Mixolydian'],c:0,why:'All four chords come from A natural minor, and A minor pentatonic is five of its notes.'}}
];
